### ISSUE TITLE
Figure of example plot is incomplete

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/Reporting-Engine#174]
When running the Aciclovir example in the Reporting Engine, Figure 2 (Vergin 200 mg PO) is lacking the 2nd set of experimental data. As a consequence, the legend is also wrong. See attached picture.

![002_plotTimeProfile](https://user-images.githubusercontent.com/27352743/58472308-482b4580-8146-11e9-9126-e5a681b1bd68.png)
 
Compare this with the corresponding PK-Sim figure:
![PK-Sim_Figure2](https://user-images.githubusercontent.com/27352743/58472381-6ee97c00-8146-11e9-9bb5-cb3130c4ea0b.jpg)

**Comment by UlrichSi** [comment]
Project folders

[01_Aciclovir.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3227520/01_Aciclovir.zip)

**Comment by pchelle** [comment]
Yes, I noticed yesterday as well, the error bars were shifting the legend, it will be fixed in the next PR.

**Comment by Yuri05** [comment]
fixed with https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/178

**Comment by UlrichSi** [comment]
There are still remaining issues with the aciclovir plots.
1. In the 200 mg tablet plot, only one set of experimental data is plotted. Only the legend shows two.
2. In both tablet plots (002 and 003), the legends do not match with what is plotted. See attached graphs.

![grafik](https://user-images.githubusercontent.com/27352743/58786956-063c4c80-85e9-11e9-9fb7-9c7ae85b622c.png)
![grafik](https://user-images.githubusercontent.com/27352743/58786964-0b999700-85e9-11e9-83f2-ea9e011ebd5e.png)

PK-Sim:
200 mg plot is already attached above, now the 400 mg plot:

![grafik](https://user-images.githubusercontent.com/27352743/58787020-2b30bf80-85e9-11e9-8ab7-72d16c201d9b.png)

**Comment by UlrichSi** [comment]
No change in plots with latest build (03-Jun, 18:09 h), issue is still remaining.

**Comment by pchelle** [comment]
Hi,
I looked into the issue: 
Left and Right axes are messing up with the legend order (observations are on the left axis, so Matlab put them before in the legend of the right axis, however it legend label is in the order of the input).
I'll let you know when the issue is fixed.

Regarding the issue where 1 experiment only is plotted, this is because, the same experiment is plotted twice on top of the other (should be ref and test, but test is plotted twice)

**Comment by msevestre** [comment]
@pchelle Do you know why TEST is plotted twice? Is this a bug in the RE code or a configuration issue ?

**Comment by pchelle** [comment]
It is the exact same RE input (except for the color). So, I think that error may come from the configuration.
![image](https://user-images.githubusercontent.com/45343665/58908056-952a9100-86dd-11e9-9fe1-aacc3a93abe7.png)

**Comment by msevestre** [comment]
@all: Where can we find the acyclovir example? It seems that the legend shows twice the same data and I suspect there is something funky going on here

**Comment by pchelle** [comment]
@msevestre, I used the one at the beginning of the issue, 
If the link below works you will have it here as well
> 
> 
> Project folders
> 
> [01_Aciclovir.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3227520/01_Aciclovir.zip)

**Comment by msevestre** [comment]
This is an error in the snapshot somehow
```
        {
              "Name": "Vergin 1995.200mg.oral.test-Aciclovir-Peripheral Venous Blood-Plasma-conc ",
              "X": "Vergin 1995.200mg.oral.test|time ",
              "Y": "Vergin 1995.200mg.oral.test|ObservedData|Peripheral Venous Blood|Plasma|Aciclovir|conc ",
              "CurveOptions": {
                "Color": "#00C0C0",
                "LegendIndex": 6,
                "LineStyle": "None",
                "Symbol": "Circle"
              }
            },
            {
              "Name": "Vergin 1995.200mg.oral.test-Aciclovir-Peripheral Venous Blood-Plasma-conc ",
              "X": "Vergin 1995.200mg.oral.test|time ",
              "Y": "Vergin 1995.200mg.oral.test|ObservedData|Peripheral Venous Blood|Plasma|Aciclovir|conc ",
              "CurveOptions": {
                "Color": "#C000C0",
                "LegendIndex": 7,
                "LineStyle": "None",
                "Symbol": "Circle"
              }
            }
```

The graph is referencing the same curve twice. 
@Yuri05 RE works as expected.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/59018635-54816380-8814-11e9-97cb-36d57c4fdbd7.png)

Loading from snapshot in pksim. Same issue

**Comment by Yuri05** [comment]
ok, seems to be an issue with an example project Aciclovir.
Closing in favor of https://github.com/Open-Systems-Pharmacology/Example_Aciclovir/issues/3
